[tool.poetry]
name = "wnsap"
version = "0.1.5"
description = ""
authors = ["woni <320753691@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
